<?php
/**
 * True Chain Infrastructure Company - configuration sample.
 *
 * Do not edit this file. The real configuration is written to
 * app/config.php automatically when you run /install.php.
 */
return [
    'db' => [
        'driver'  => 'mysql',          // 'mysql' (GoDaddy) or 'sqlite'
        'host'    => 'localhost',
        'port'    => '3306',
        'name'    => 'your_database',
        'user'    => 'your_db_user',
        'pass'    => 'your_db_password',
        'prefix'  => 'tcic_',
        'sqlite_path' => __DIR__ . '/storage/tcic.sqlite',
    ],
    'app' => [
        'key'            => 'generate-a-64-char-random-string',
        'session_name'   => 'TCICSESS',
        'session_idle'   => 3600,      // admin idle timeout, seconds
        'debug'          => false,
    ],
];
